
services:

  auth-service:
    build: ./services/auth-service
    command: sh -c "npm run dev"
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
      - ./shared:/app/shared
    env_file: ./services/auth-service/.env
    expose: 
      - "4000"
    depends_on:
      - db

  auth-migrate:
    build: ./services/auth-service
    command: npm run migrate
    volumes:
      - ./services/auth-service:/app
      - ./services/auth-service/src/db/migrations:/app/migrations
      - /app/node_modules
    env_file: ./services/auth-service/.env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: authDB
    ports: ["5433:5432"]

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./gateways/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service

volumes:
  db_data: