name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  auth-service-test:
    name: Run auth service test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/auth-service
    
    steps:  
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up Node env
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Docker image
        run: docker build -t auth-service-test .

      - name: Run all dependent services in seperate containers
        run: docker compose up

      - name: Run test inside the container
        run: npm test




      





